import type { Language } from '../hooks/useSettings'

const id = {
  logo: '#',

  home: {
    title: '#hashtagaja',
    desc: ['ketik hashtag.', 'dapat ruangan.', 'hilang dalam 7 hari.'],
    featuresTitle: 'cara kerja',
    inputPlaceholder: '#ruangan-kamu',
    enterBtn: 'masuk →',
    footer: 'berbagi tanpa jejak',
    hints: [
      'ruangan otomatis terhapus setelah 7 hari',
      'berbagi file hingga 10mb',
    ],
    errors: {
      empty: 'ketik hashtag untuk melanjutkan',
      tooShort: 'hashtag minimal 2 karakter',
      tooLong: 'hashtag maksimal 32 karakter',
    },
  },

  room: {
    backBtn: '←',
    backTitle: 'kembali ke beranda',
    backFromError: '← kembali',
    online: 'online',
    expiresIn: 'berakhir dalam',
    expired: 'kedaluwarsa',
    today: 'hari ini',
    loading: 'bergabung',
    loadingCursor: '_',
    emptyDesc: 'belum ada pesan. mulai bicara.',
    inputPlaceholder: 'tulis pesan...',
    attachTitle: 'lampirkan file',
    sendTitle: 'kirim',
    inputHint: 'enter untuk kirim · shift+enter untuk baris baru · + untuk lampirkan file',
    uploading: '…',
    sending: '…',
    attachIdle: '+',
    sendIdle: '↑',
    fileIcon: '⬡',
    fileDl: '↓',
    youLabel: 'kamu',
    copyBtn: 'salin',
    copiedBtn: 'tersalin',
    dragLabel: 'lepaskan untuk upload ↑',
    leaveTitle: 'keluar dari ruangan?',
    leaveDesc: 'kamu bisa kembali kapan saja dengan hashtag yang sama.',
    leaveCancel: 'batal',
    leaveConfirm: 'keluar',
    settingsBtn: 'pengaturan',
    badgeOwner: 'pemilik',
    badgeGuest: 'tamu',
    badgeNoOwner: 'publik',
    ownerOffline: 'pemilik ruangan sedang offline — ruangan mungkin akan segera dihapus',
    roomDeleted: 'ruangan dihapus. mengalihkan ke beranda...',
    roomExpiredTitle: 'ruangan kedaluwarsa',
    roomExpiredDesc: 'ruangan ini sudah tidak aktif dan telah dihapus.',
    roomExpiredBtn: 'kembali ke beranda',
    roomDeletedTitle: 'ruangan dihapus',
    roomDeletedDesc: 'pemilik telah menutup ruangan ini.',
    roomDeletedBtn: 'kembali ke beranda',
    fileSizeWarning: 'file lebih dari 10mb, yakin mau upload?',
    fileSizeWarningConfirm: 'ya, upload',
    deleteRoomTitle: 'tutup ruangan ini?',
    deleteRoomDesc: 'semua pesan dan file akan terhapus selamanya. tidak bisa dibatalkan.',
    deleteRoomBtn: 'tutup ruangan',
    deleteRoomConfirm: 'ya, tutup',
    deleteRoomCancel: 'batal',
    fileSizeWarningCancel: 'batal',
    errors: {
      loadFailed: 'gagal memuat ruangan. periksa koneksi kamu.',
      sendFailed: 'gagal mengirim pesan',
      uploadFailed: 'gagal mengunggah file',
      fileTooLarge: 'file terlalu besar (maks 10mb)',
      fileLimitReached: 'batas file ruangan tercapai (maks 20 file)',
      roomLimitReached: 'terlalu banyak ruangan dibuat, coba lagi dalam 1 jam',
    },
  },

  settings: {
    title: 'pengaturan',
    closeBtn: 'tutup',
    languageLabel: 'bahasa',
    languages: { id: 'Indonesia', en: 'English' },
    fontLabel: 'font',
    aboutTitle: 'tentang',
    aboutDesc: 'ruangan obrolan sementara berbasis hashtag. tidak perlu akun. semua pesan dan file terhapus otomatis setelah 7 hari.',
    madeBy: 'dibuat oleh',
    sourceCode: 'kode sumber',
    license: 'lisensi',
    builtWith: 'dibangun dengan',
    saveBtn: 'simpan',
  },

  admin: {
    login: {
      title: 'admin',
      subtitle: 'masuk untuk melanjutkan',
      emailLabel: 'email',
      emailPlaceholder: 'kamu@contoh.com',
      passwordLabel: 'kata sandi',
      passwordPlaceholder: '••••••••',
      submitBtn: 'masuk →',
      submittingBtn: 'sedang masuk...',
    },
    dashboard: {
      title: 'admin',
      searchPlaceholder: 'cari ruangan...',
      signOut: 'keluar',
      sidebarLoading: 'memuat_',
      sidebarEmpty: 'tidak ada ruangan',
      mainEmpty: 'pilih ruangan untuk melihat detail',
      mainLoading: 'memuat_',
      expired: 'kedaluwarsa',
      stats: { rooms: 'ruangan', active: 'aktif', expired: 'kedaluwarsa' },
      room: { created: 'dibuat', expiresIn: 'berakhir dalam', expired: 'kedaluwarsa', messages: 'pesan', deleteBtn: 'hapus ruangan' },
      sections: { messages: 'pesan', files: 'file', noMessages: 'belum ada pesan', noFiles: 'belum ada file' },
      confirm: { title: (type: string) => `hapus ${type}?`, desc: 'tindakan ini tidak bisa dibatalkan.', cancel: 'batal', delete: 'hapus' },
      toast: { roomDeleted: 'ruangan dihapus', messageDeleted: 'pesan dihapus', roomError: 'gagal menghapus ruangan', messageError: 'gagal menghapus pesan' },
    },
  },
}

const en: typeof id = {
  logo: '#',

  home: {
    title: '#hashtagaja',
    desc: ['type a hashtag.', 'get a room.', 'gone in 7 days.'],
    featuresTitle: 'how it works',
    inputPlaceholder: '#your-room',
    enterBtn: 'enter →',
    footer: 'share without a trace',
    hints: [
      'rooms auto-delete after 7 days',
      'share files up to 10mb',
    ],
    errors: {
      empty: 'enter a hashtag to continue',
      tooShort: 'hashtag must be at least 2 characters',
      tooLong: 'hashtag must be 32 characters or less',
    },
  },

  room: {
    backBtn: '←',
    backTitle: 'back to home',
    backFromError: '← back',
    online: 'online',
    expiresIn: 'expires in',
    expired: 'expired',
    today: 'today',
    loading: 'joining',
    loadingCursor: '_',
    emptyDesc: 'no messages yet. say something.',
    inputPlaceholder: 'type a message...',
    attachTitle: 'attach file',
    sendTitle: 'send',
    inputHint: 'enter to send · shift+enter for new line · + to attach file',
    uploading: '…',
    sending: '…',
    attachIdle: '+',
    sendIdle: '↑',
    fileIcon: '⬡',
    fileDl: '↓',
    youLabel: 'you',
    copyBtn: 'copy',
    copiedBtn: 'copied',
    dragLabel: 'drop to upload ↑',
    leaveTitle: 'leave room?',
    leaveDesc: 'you can come back anytime with the same hashtag.',
    leaveCancel: 'cancel',
    leaveConfirm: 'leave',
    settingsBtn: 'settings',
    badgeOwner: 'owner',
    badgeGuest: 'guest',
    badgeNoOwner: 'public',
    ownerOffline: 'room owner is offline — room may be deleted soon',
    roomDeleted: 'room deleted. redirecting to home...',
    roomExpiredTitle: 'room expired',
    roomExpiredDesc: 'this room has expired and is no longer available.',
    roomExpiredBtn: 'back to home',
    roomDeletedTitle: 'room closed',
    roomDeletedDesc: 'the owner has closed this room.',
    roomDeletedBtn: 'back to home',
    fileSizeWarning: 'file is over 10mb, are you sure?',
    fileSizeWarningConfirm: 'yes, upload',
    deleteRoomTitle: 'close this room?',
    deleteRoomDesc: 'all messages and files will be permanently deleted. this cannot be undone.',
    deleteRoomBtn: 'close room',
    deleteRoomConfirm: 'yes, close',
    deleteRoomCancel: 'cancel',
    fileSizeWarningCancel: 'cancel',
    errors: {
      loadFailed: 'failed to load room. check your connection.',
      sendFailed: 'failed to send message',
      uploadFailed: 'failed to upload file',
      fileTooLarge: 'file too large (max 10mb)',
      fileLimitReached: 'file limit reached for this room (max 20 files)',
      roomLimitReached: 'too many rooms created, try again in 1 hour',
    },
  },

  settings: {
    title: 'settings',
    closeBtn: 'close',
    languageLabel: 'language',
    languages: { id: 'Indonesia', en: 'English' },
    fontLabel: 'font',
    aboutTitle: 'about',
    aboutDesc: 'hashtag-based temporary chat rooms. no account needed. all messages and files are automatically deleted after 7 days.',
    madeBy: 'made by',
    sourceCode: 'source code',
    license: 'license',
    builtWith: 'built with',
    saveBtn: 'save',
  },

  admin: {
    login: {
      title: 'admin',
      subtitle: 'sign in to continue',
      emailLabel: 'email',
      emailPlaceholder: 'you@example.com',
      passwordLabel: 'password',
      passwordPlaceholder: '••••••••',
      submitBtn: 'sign in →',
      submittingBtn: 'signing in...',
    },
    dashboard: {
      title: 'admin',
      searchPlaceholder: 'search rooms...',
      signOut: 'sign out',
      sidebarLoading: 'loading_',
      sidebarEmpty: 'no rooms found',
      mainEmpty: 'select a room to view details',
      mainLoading: 'loading_',
      expired: 'expired',
      stats: { rooms: 'rooms', active: 'active', expired: 'expired' },
      room: { created: 'created', expiresIn: 'expires in', expired: 'expired', messages: 'messages', deleteBtn: 'delete room' },
      sections: { messages: 'messages', files: 'files', noMessages: 'no messages', noFiles: 'no files' },
      confirm: { title: (type: string) => `delete ${type}?`, desc: 'this cannot be undone.', cancel: 'cancel', delete: 'delete' },
      toast: { roomDeleted: 'room deleted', messageDeleted: 'message deleted', roomError: 'failed to delete room', messageError: 'failed to delete message' },
    },
  },
}

const translations = { id, en }

export function getContent(lang: Language) {
  return translations[lang] ?? translations.id
}

// default export for pages that don't have settings yet (admin)
export const content = id
